framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'de'
    translator:
        fallbacks: ['de']
    session:
        handler_id: ~
    php_errors:
        log: true
    assets:
        version: '%assets_version%'
    templating:
        engines: ['twig']
