framework:
    secret: '%env(APP_SECRET)%'
    default_locale: 'de'
    translator:
        fallbacks: ['de']
    session:
        handler_id: ~
    php_errors:
        log: true
    templating:
        engines: ['twig']
    cache:
        app: cache.adapter.redis
        pools:
            app.cache.geocoding:
                adapter: cache.app
                default_lifetime: 600