security:
    providers:
        database_provider:
            entity:
                class: AppBundle:User
                property: username

    # ...

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            pattern: ^/admin
            http_basic: ~
            provider: database_provider
            logout: ~

        main:
            anonymous: true
            oauth:
                resource_owners:
                    twitter:  '/login/check-twitter'
                login_path: /login
                failure_path: /login
                oauth_user_provider:
                    service: App\UserProvider\LuftUserProvider
                default_target_path: /twitter-success
            logout: ~

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }

    role_hierarchy:
        ROLE_ADMIN:
            - ROLE_USER

    access_decision_manager:
        strategy: unanimous
